# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_eval_engine.ipynb.

"""Tests for the decomposed multimodal pipeline.

Tests the 4-stage pipeline: prep → single → ablation → merge.
Each function is tested independently with synthetic data.
"""

import json
import tempfile
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from kreview.eval_engine import (
    multimodal_ablation,
    multimodal_merge,
    multimodal_prep,
    multimodal_single,
)


# ── Fixtures ──────────────────────────────────────────────────────────────────


def _write_json(path: Path, data: dict) -> None:
    """Helper to write JSON files."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        json.dump(data, f, indent=2, default=str)


@pytest.fixture()
def sample_evaluator_jsons(tmp_path: Path) -> Path:
    """Create synthetic model_results.json files for 3 evaluators.

    Each evaluator has LR and RF OOF probabilities for 20 samples.
    """
    np.random.seed(42)
    n_samples = 20
    labels = [0] * 10 + [1] * 10
    sample_ids = [f"sample_{i}" for i in range(n_samples)]

    for eval_name in ["EvalA", "EvalB", "EvalC"]:
        lr_probs = np.random.rand(n_samples).tolist()
        rf_probs = np.random.rand(n_samples).tolist()

        data = {
            "evaluator": eval_name,
            "oof_labels": labels,
            "oof_sample_ids": sample_ids,
            "lr_oof_probs": lr_probs,
            "rf_oof_probs": rf_probs,
            "auc_lr": float(np.random.uniform(0.6, 0.9)),
            "auc_rf": float(np.random.uniform(0.6, 0.9)),
            "best_model": "rf",
            "best_auc": float(np.random.uniform(0.7, 0.9)),
        }
        _write_json(tmp_path / f"{eval_name}_model_results.json", data)

    return tmp_path


@pytest.fixture()
def stacking_parquet(tmp_path: Path) -> Path:
    """Create a synthetic stacking_matrix.parquet."""
    np.random.seed(42)
    n_samples = 20
    df = pd.DataFrame(
        {
            "EvalA_lr": np.random.rand(n_samples),
            "EvalA_rf": np.random.rand(n_samples),
            "EvalB_lr": np.random.rand(n_samples),
            "EvalB_rf": np.random.rand(n_samples),
            "EvalC_lr": np.random.rand(n_samples),
            "EvalC_rf": np.random.rand(n_samples),
            "_label": [0] * 10 + [1] * 10,
        }
    )
    path = tmp_path / "stacking_matrix.parquet"
    df.to_parquet(path, index=False)
    return path


@pytest.fixture()
def stacking_results(tmp_path: Path, stacking_parquet: Path) -> Path:
    """Run multimodal_single for rf and xgb, producing partial JSONs."""
    for model in ["rf", "xgb"]:
        multimodal_single(
            stacking_matrix_path=stacking_parquet,
            model_name=model,
            n_folds=3,
            random_state=42,
            output_dir=tmp_path,
        )
    return tmp_path


@pytest.fixture()
def prep_metadata(tmp_path: Path) -> Path:
    """Create a synthetic prep_metadata.json."""
    metadata = {
        "stacking_columns": ["EvalA_lr", "EvalA_rf", "EvalB_lr", "EvalB_rf"],
        "stacking_shape": [20, 4],
        "n_evaluators": 2,
        "evaluators": ["EvalA", "EvalB"],
        "single_evaluator_aucs": {"EvalA": 0.85, "EvalB": 0.80},
        "best_single_evaluator": "EvalA",
        "best_single_auc": 0.85,
        "multimodal_selection": "mi",
        "top_percentile": 10.0,
        "has_raw_features": False,
        "raw_shape": None,
    }
    path = tmp_path / "prep_metadata.json"
    _write_json(path, metadata)
    return path


# ── Tests: multimodal_prep ────────────────────────────────────────────────────


class TestMultimodalPrep:
    """Tests for multimodal_prep (Stage 1)."""

    def test_produces_stacking_parquet(self, sample_evaluator_jsons, tmp_path):
        """Prep should produce stacking_matrix.parquet."""
        out = tmp_path / "prep_out"
        multimodal_prep(
            results_dir=sample_evaluator_jsons,
            output_dir=out,
        )
        assert (out / "stacking_matrix.parquet").exists()
        assert (out / "prep_metadata.json").exists()

    def test_stacking_matrix_has_label_column(self, sample_evaluator_jsons, tmp_path):
        """Stacking parquet should contain _label column."""
        out = tmp_path / "prep_out"
        multimodal_prep(
            results_dir=sample_evaluator_jsons,
            output_dir=out,
        )
        df = pd.read_parquet(out / "stacking_matrix.parquet")
        assert "_label" in df.columns

    def test_metadata_has_required_keys(self, sample_evaluator_jsons, tmp_path):
        """Prep metadata JSON should contain all required keys."""
        out = tmp_path / "prep_out"
        metadata = multimodal_prep(
            results_dir=sample_evaluator_jsons,
            output_dir=out,
        )
        required_keys = {
            "stacking_columns",
            "stacking_shape",
            "n_evaluators",
            "evaluators",
            "single_evaluator_aucs",
            "best_single_evaluator",
            "best_single_auc",
        }
        assert required_keys.issubset(metadata.keys())

    def test_metadata_n_evaluators_correct(self, sample_evaluator_jsons, tmp_path):
        """Number of evaluators should match JSON files."""
        out = tmp_path / "prep_out"
        metadata = multimodal_prep(
            results_dir=sample_evaluator_jsons,
            output_dir=out,
        )
        assert metadata["n_evaluators"] == 3  # EvalA, EvalB, EvalC

    def test_empty_results_dir_raises(self, tmp_path):
        """Empty results dir should raise ValueError."""
        empty_dir = tmp_path / "empty"
        empty_dir.mkdir()
        with pytest.raises(ValueError, match="No .* files in"):
            multimodal_prep(
                results_dir=empty_dir,
                output_dir=tmp_path / "out",
            )

    def test_nonexistent_results_dir_raises(self, tmp_path):
        """Non-existent results dir should raise FileNotFoundError."""
        with pytest.raises(FileNotFoundError):
            multimodal_prep(
                results_dir=tmp_path / "nonexistent",
                output_dir=tmp_path / "out",
            )


# ── Tests: multimodal_single ─────────────────────────────────────────────────


class TestMultimodalSingle:
    """Tests for multimodal_single (Stage 2)."""

    def test_produces_stacking_json(self, stacking_parquet, tmp_path):
        """Single should produce stacking_{model}_results.json."""
        out = tmp_path / "single_out"
        multimodal_single(
            stacking_matrix_path=stacking_parquet,
            model_name="rf",
            n_folds=3,
            random_state=42,
            output_dir=out,
        )
        assert (out / "stacking_rf_results.json").exists()

    def test_auc_in_output(self, stacking_parquet, tmp_path):
        """Output JSON should contain auc_stacking_rf."""
        out = tmp_path / "single_out"
        results = multimodal_single(
            stacking_matrix_path=stacking_parquet,
            model_name="rf",
            n_folds=3,
            random_state=42,
            output_dir=out,
        )
        assert "auc_stacking_rf" in results
        assert isinstance(results["auc_stacking_rf"], float)
        assert 0 <= results["auc_stacking_rf"] <= 1

    def test_lr_model(self, stacking_parquet, tmp_path):
        """LR model should also work."""
        out = tmp_path / "single_out"
        results = multimodal_single(
            stacking_matrix_path=stacking_parquet,
            model_name="lr",
            n_folds=3,
            random_state=42,
            output_dir=out,
        )
        assert "auc_stacking_lr" in results

    def test_xgb_model(self, stacking_parquet, tmp_path):
        """XGB model should work."""
        out = tmp_path / "single_out"
        results = multimodal_single(
            stacking_matrix_path=stacking_parquet,
            model_name="xgb",
            n_folds=3,
            random_state=42,
            output_dir=out,
        )
        assert "auc_stacking_xgb" in results

    def test_delta_vs_best_single(self, stacking_parquet, tmp_path):
        """When best_single_auc is provided, delta should be computed."""
        out = tmp_path / "single_out"
        results = multimodal_single(
            stacking_matrix_path=stacking_parquet,
            model_name="rf",
            n_folds=3,
            random_state=42,
            best_single_auc=0.75,
            output_dir=out,
        )
        assert "stacking_rf_vs_best_single" in results

    def test_nonexistent_stacking_matrix_raises(self, tmp_path):
        """Missing stacking matrix should raise FileNotFoundError."""
        with pytest.raises(FileNotFoundError, match="Stacking matrix not found"):
            multimodal_single(
                stacking_matrix_path=tmp_path / "nonexistent.parquet",
                model_name="rf",
                output_dir=tmp_path,
            )

    def test_unknown_model_raises(self, stacking_parquet, tmp_path):
        """Unknown model should raise ValueError."""
        with pytest.raises(ValueError, match="Unknown model"):
            multimodal_single(
                stacking_matrix_path=stacking_parquet,
                model_name="not_a_model",
                output_dir=tmp_path,
            )


# ── Tests: multimodal_ablation ────────────────────────────────────────────────


class TestMultimodalAblation:
    """Tests for multimodal_ablation (Stage 3)."""

    def test_produces_ablation_json(self, stacking_parquet, stacking_results, tmp_path):
        """Ablation should produce ablation_results.json."""
        out = tmp_path / "ablation_out"
        multimodal_ablation(
            stacking_matrix_path=stacking_parquet,
            stacking_results_dir=stacking_results,
            n_folds=3,
            random_state=42,
            output_dir=out,
        )
        assert (out / "ablation_results.json").exists()

    def test_ablation_has_model_key(self, stacking_parquet, stacking_results, tmp_path):
        """Ablation should identify the best stacking model."""
        out = tmp_path / "ablation_out"
        results = multimodal_ablation(
            stacking_matrix_path=stacking_parquet,
            stacking_results_dir=stacking_results,
            n_folds=3,
            random_state=42,
            output_dir=out,
        )
        assert "ablation_model" in results
        assert results["ablation_model"] in ("rf", "xgb", "lr")

    def test_ablation_has_per_evaluator_deltas(
        self, stacking_parquet, stacking_results, tmp_path
    ):
        """Each evaluator should have a delta in ablation results."""
        out = tmp_path / "ablation_out"
        results = multimodal_ablation(
            stacking_matrix_path=stacking_parquet,
            stacking_results_dir=stacking_results,
            n_folds=3,
            random_state=42,
            output_dir=out,
        )
        ablation = results["ablation"]
        assert len(ablation) > 0
        for eval_name, info in ablation.items():
            if "error" not in info:
                assert "delta" in info
                assert "auc_without" in info

    def test_no_results_raises(self, stacking_parquet, tmp_path):
        """No stacking results should raise ValueError."""
        empty_dir = tmp_path / "empty"
        empty_dir.mkdir()
        with pytest.raises(ValueError, match="No valid stacking results"):
            multimodal_ablation(
                stacking_matrix_path=stacking_parquet,
                stacking_results_dir=empty_dir,
                output_dir=tmp_path / "out",
            )


# ── Tests: multimodal_merge ──────────────────────────────────────────────────


class TestMultimodalMerge:
    """Tests for multimodal_merge (Stage 4)."""

    def test_produces_unified_json(
        self, stacking_results, prep_metadata, tmp_path
    ):
        """Merge should produce multimodal_results.json."""
        out = tmp_path / "merge_out"
        multimodal_merge(
            stacking_results_dir=stacking_results,
            prep_metadata_path=prep_metadata,
            output_dir=out,
        )
        assert (out / "multimodal_results.json").exists()

    def test_schema_has_strategy(self, stacking_results, prep_metadata, tmp_path):
        """Merged JSON should have 'strategy' key."""
        out = tmp_path / "merge_out"
        results = multimodal_merge(
            stacking_results_dir=stacking_results,
            prep_metadata_path=prep_metadata,
            output_dir=out,
        )
        assert results["strategy"] == "multimodal"

    def test_stacking_key_contains_aucs(
        self, stacking_results, prep_metadata, tmp_path
    ):
        """Merged stacking dict should contain AUC keys."""
        out = tmp_path / "merge_out"
        results = multimodal_merge(
            stacking_results_dir=stacking_results,
            prep_metadata_path=prep_metadata,
            output_dir=out,
        )
        stacking = results["stacking"]
        auc_keys = [k for k in stacking if k.startswith("auc_stacking_")]
        assert len(auc_keys) >= 2  # rf + xgb at minimum

    def test_merge_with_ablation(
        self, stacking_results, prep_metadata, stacking_parquet, tmp_path
    ):
        """Merge with ablation should include ablation keys."""
        # Run ablation first
        abl_out = tmp_path / "abl"
        multimodal_ablation(
            stacking_matrix_path=stacking_parquet,
            stacking_results_dir=stacking_results,
            n_folds=3,
            random_state=42,
            output_dir=abl_out,
        )

        out = tmp_path / "merge_out"
        results = multimodal_merge(
            stacking_results_dir=stacking_results,
            prep_metadata_path=prep_metadata,
            ablation_path=abl_out / "ablation_results.json",
            output_dir=out,
        )
        assert "ablation" in results
        assert "ablation_model" in results

    def test_missing_metadata_raises(self, tmp_path):
        """Missing prep metadata should raise FileNotFoundError."""
        with pytest.raises(FileNotFoundError, match="Prep metadata not found"):
            multimodal_merge(
                stacking_results_dir=tmp_path,
                prep_metadata_path=tmp_path / "nonexistent.json",
                output_dir=tmp_path / "out",
            )

    def test_merge_without_stacking_files_warns(self, prep_metadata, tmp_path):
        """Merge with no stacking files should produce empty stacking dict."""
        empty_dir = tmp_path / "empty"
        empty_dir.mkdir()
        out = tmp_path / "merge_out"
        results = multimodal_merge(
            stacking_results_dir=empty_dir,
            prep_metadata_path=prep_metadata,
            output_dir=out,
        )
        # Should succeed but with empty stacking
        assert results["stacking"] == {}


# ── Tests: Full Pipeline Integration ─────────────────────────────────────────


class TestMultimodalFullPipeline:
    """End-to-end test of the decomposed pipeline."""

    def test_prep_single_ablation_merge(self, sample_evaluator_jsons, tmp_path):
        """Full pipeline: prep → single(rf,xgb) → ablation → merge."""
        prep_out = tmp_path / "prep"
        single_out = tmp_path / "single"
        abl_out = tmp_path / "ablation"
        merge_out = tmp_path / "merge"

        # Stage 1: Prep
        metadata = multimodal_prep(
            results_dir=sample_evaluator_jsons,
            output_dir=prep_out,
        )
        assert (prep_out / "stacking_matrix.parquet").exists()
        assert (prep_out / "prep_metadata.json").exists()

        # Stage 2: Single × 2
        for model in ["rf", "xgb"]:
            multimodal_single(
                stacking_matrix_path=prep_out / "stacking_matrix.parquet",
                model_name=model,
                n_folds=3,
                random_state=42,
                best_single_auc=metadata["best_single_auc"],
                output_dir=single_out,
            )
        assert (single_out / "stacking_rf_results.json").exists()
        assert (single_out / "stacking_xgb_results.json").exists()

        # Stage 3: Ablation
        multimodal_ablation(
            stacking_matrix_path=prep_out / "stacking_matrix.parquet",
            stacking_results_dir=single_out,
            n_folds=3,
            random_state=42,
            output_dir=abl_out,
        )
        assert (abl_out / "ablation_results.json").exists()

        # Stage 4: Merge
        results = multimodal_merge(
            stacking_results_dir=single_out,
            prep_metadata_path=prep_out / "prep_metadata.json",
            ablation_path=abl_out / "ablation_results.json",
            output_dir=merge_out,
        )

        # Verify merged output
        assert (merge_out / "multimodal_results.json").exists()
        assert results["strategy"] == "multimodal"
        assert "stacking" in results
        assert "ablation" in results
        assert "ablation_model" in results
        assert results["n_evaluators"] == 3

        # Verify AUCs exist for both models
        stacking = results["stacking"]
        assert "auc_stacking_rf" in stacking
        assert "auc_stacking_xgb" in stacking
