# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/features/22b_breakpoint_motif_genomewide.ipynb.

# %% ../../nbs/features/22b_breakpoint_motif_genomewide.ipynb #932a57c3
from __future__ import annotations
import pandas as pd
import structlog
from ..eval_engine import FeatureEvaluator

log = structlog.get_logger()

# %% auto #0
__all__ = ["log", "BreakPointMotifGenomewideEvaluator"]


# %% ../../nbs/features/22b_breakpoint_motif_genomewide.ipynb #0b410faf
class BreakPointMotifGenomewideEvaluator(FeatureEvaluator):
    """Extracts 4-mer adjacent breakpoint motifs for genomewide regions."""

    name = "BreakPointMotifGenomewide"
    source_file = ".BreakPointMotif.parquet"
    tier = 3
    category = "motifs"

    def extract(self, df: pd.DataFrame) -> dict[str, float]:
        extracted = {}
        try:
            if df.empty:
                return extracted
            cols = set(df.columns)

            if "Motif" in cols and "Frequency" in cols:
                for row in df.to_dict("records"):
                    m = str(row["Motif"])
                    if pd.notna(row["Frequency"]):
                        extracted[f"bpmotif_gw_{m}"] = float(row["Frequency"])

            return extracted
        except Exception as e:
            log.exception("extraction_failed", evaluator=self.name, error=str(e))
            return {}
