# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/features/23_endmotif_1mer.ipynb.

# %% ../../nbs/features/23_endmotif_1mer.ipynb #2806f578
from __future__ import annotations
import pandas as pd
import structlog
from ..eval_engine import FeatureEvaluator, parse_array

log = structlog.get_logger()

# %% auto #0
__all__ = ["log", "EndMotif1merEvaluator"]


# %% ../../nbs/features/23_endmotif_1mer.ipynb #b74ea526
class EndMotif1merEvaluator(FeatureEvaluator):
    """Extracts 1-mer fragment end base frequencies."""

    name = "EndMotif1mer"
    source_file = ".EndMotif1mer.parquet"
    tier = 3
    category = "motifs"

    def extract(self, df: pd.DataFrame) -> dict[str, float]:
        extracted = {}
        try:
            if df.empty:
                return extracted
            cols = set(df.columns)

            if "base" in cols and "fraction" in cols:
                for row in df.to_dict("records"):
                    b = str(row["base"])
                    if pd.notna(row["fraction"]):
                        extracted[f"base_1mer_{b}"] = float(row["fraction"])

            return extracted
        except Exception as e:
            log.exception("extraction_failed", evaluator=self.name, error=str(e))
            return {}
