# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/features/11_fsc_binlevel.ipynb.

# %% ../../nbs/features/11_fsc_binlevel.ipynb #8b4756c4
from __future__ import annotations
import pandas as pd
import structlog
from ..eval_engine import FeatureEvaluator

log = structlog.get_logger()


# %% auto #0
__all__ = ["log", "FSCBinEvaluator"]


# %% ../../nbs/features/11_fsc_binlevel.ipynb #066dbdb5
class FSCBinEvaluator(FeatureEvaluator):
    """Extracts genome-wide and per-chromosome fragment size configurations."""

    name = "FSC_binlevel"
    source_file = ".FSC.ontarget.parquet"
    tier = 1
    category = "fragmentation"

    def extract(self, df: pd.DataFrame) -> dict[str, float]:
        extracted = {}
        try:
            if df.empty:
                return extracted

            cols = set(df.columns)
            ratios = ["core_short_ratio", "mono_nucl_ratio", "long_ratio"]

            # Global median over all bins
            for r in ratios:
                if r in cols:
                    extracted[f"global_{r}_median"] = float(df[r].median())

            if "normalized_depth" in cols:
                extracted["global_normalized_depth_median"] = float(
                    df["normalized_depth"].median()
                )

            # Per-chromosome aggregates
            if "chrom" in cols:
                chroms = [f"chr{i}" for i in range(1, 23)] + ["chrX", "chrY"]
                for c in chroms:
                    sub = df[df["chrom"] == c]
                    if sub.empty:
                        continue
                    for r in ratios:
                        if r in cols:
                            extracted[f"{c}_{r}_median"] = float(sub[r].median())

            return extracted
        except Exception as e:
            log.warning("fsc_binlevel_extraction_failed", error=str(e))
            return {}
