# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/features/12_fsc_regions.ipynb.

# %% ../../nbs/features/12_fsc_regions.ipynb #fdc37aee
from __future__ import annotations
import pandas as pd
import structlog
from ..eval_engine import FeatureEvaluator

log = structlog.get_logger()


# %% auto #0
__all__ = ['log', 'FSCRegionsEvaluator']

# %% ../../nbs/features/12_fsc_regions.ipynb #f85bbceb
class FSCRegionsEvaluator(FeatureEvaluator):
    """Extracts wide net ratios for targeted panels."""

    name = "FSC_regions"
    source_file = ".FSC.regions.parquet"
    tier = 1
    category = "fragmentation"

    def extract(self, df: pd.DataFrame) -> dict[str, float]:
        extracted = {}
        try:
            if df.empty:
                return extracted

            cols = set(df.columns)
            ratios = [
                "ultra_short_ratio",
                "core_short_ratio",
                "mono_nucl_ratio",
                "di_nucl_ratio",
                "long_ratio",
            ]

            # Global
            for r in ratios:
                if r in cols:
                    extracted[f"global_{r}_mean"] = float(df[r].mean())
                    extracted[f"global_{r}_std"] = float(df[r].std())

            # Variance across genes
            if "gene" in cols:
                for r in ratios:
                    if r in cols:
                        gene_means = df.groupby("gene")[r].mean()
                        if len(gene_means) > 1:
                            extracted[f"{r}_variance_across_genes"] = float(
                                gene_means.std()
                            )

            return extracted
        except Exception as e:
            log.exception("extraction_failed", evaluator=self.name, error=str(e))
            return {}
