# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/features/12_fsc_regions.ipynb.

# %% ../../nbs/features/12_fsc_regions.ipynb #e2400207
from __future__ import annotations
import pandas as pd
import structlog
from ..eval_engine import FeatureEvaluator

log = structlog.get_logger()


# %% auto #0
__all__ = ["log", "FSCRegionsEvaluator"]


# %% ../../nbs/features/12_fsc_regions.ipynb #cf087b02
class FSCRegionsEvaluator(FeatureEvaluator):
    """Extracts variance of fragment ratios partitioned by specific targeted regions."""

    name = "FSC_regions"
    source_file = ".FSC.regions.parquet"
    tier = 1
    category = "fragmentation"

    def extract(self, df: pd.DataFrame) -> dict[str, float]:
        extracted = {}
        try:
            if df.empty:
                return extracted

            cols = set(df.columns)
            ratios = ["core_short_ratio", "mono_nucl_ratio"]

            for r in ratios:
                if r in cols:
                    extracted[f"regional_{r}_mean"] = float(df[r].mean())
                    extracted[f"regional_{r}_std"] = float(df[r].std())

            # Aggregate per gene if region_mapped
            if "gene" in cols and "core_short_ratio" in cols:
                gene_means = df.groupby("gene")["core_short_ratio"].mean()
                extracted["core_short_ratio_variance_across_genes"] = float(
                    gene_means.std()
                )

            return extracted
        except Exception as e:
            log.warning("fsc_regions_extraction_failed", error=str(e))
            return {}
