# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/features/14_fsr.ipynb.

# %% ../../nbs/features/14_fsr.ipynb #811b6ead
from __future__ import annotations
import pandas as pd
import structlog
from ..eval_engine import FeatureEvaluator

log = structlog.get_logger()


# %% auto #0
__all__ = ["log", "FSREvaluator"]


# %% ../../nbs/features/14_fsr.ipynb #faae0815
class FSREvaluator(FeatureEvaluator):
    """Extracts the short-to-long fragment size ratio across predefined structural metrics."""

    name = "FSR"
    source_file = ".FSR.parquet"
    tier = 1
    category = "fragmentation"

    def extract(self, df: pd.DataFrame) -> dict[str, float]:
        extracted = {}
        try:
            if df.empty:
                return extracted

            cols = set(df.columns)

            # FSR file exposes global log2 ratios
            if "short_to_long_ratio" in cols:
                extracted["global_short_to_long_ratio"] = float(
                    df["short_to_long_ratio"].iloc[0]
                )
            if "p_value" in cols:
                extracted["global_fsr_p_value"] = float(df["p_value"].iloc[0])

            return extracted
        except Exception as e:
            log.warning("fsr_extraction_failed", error=str(e))
            return {}
