# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/features/14b_fsr_genomewide.ipynb.

# %% ../../nbs/features/14b_fsr_genomewide.ipynb #1699fd47
from __future__ import annotations
import pandas as pd
import structlog
from ..eval_engine import FeatureEvaluator

log = structlog.get_logger()

# %% auto #0
__all__ = ["log", "FSREvaluator"]


# %% ../../nbs/features/14b_fsr_genomewide.ipynb #3a85e316
class FSREvaluator(FeatureEvaluator):
    """Extracts the short/long fragment size ratio across genomewide bins.

    Only bins with read coverage (total_count > 0) are included in aggregation.
    Genomewide panels typically cover ~93% of bins, but the filter ensures
    uncovered bins don't contribute noise to summary statistics.
    """

    name = "FsrGenomewide"
    source_file = ".FSR.parquet"
    tier = 1
    category = "fragmentation"

    def extract(self, df: pd.DataFrame) -> dict[str, float]:
        extracted = {}
        try:
            if df.empty:
                return extracted

            # Filter to bins with actual read coverage
            if "total_count" in df.columns:
                n_total = len(df)
                df = df[df["total_count"] > 0]
                extracted["n_covered_bins"] = len(df)
                extracted["n_total_bins"] = n_total
                if df.empty:
                    log.warning(
                        "no_covered_bins",
                        evaluator=self.name,
                        total_bins=n_total,
                    )
                    return extracted

            cols = set(df.columns)
            target_metrics = [
                "short_long_ratio",
                "short_long_log2",
                "short_frac",
                "long_frac",
            ]

            for m in target_metrics:
                if m in cols:
                    extracted[f"global_{m}"] = float(df[m].median())

            return extracted
        except Exception as e:
            log.exception("extraction_failed", evaluator=self.name, error=str(e))
            return {}
