# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/features/14b_fsr_genomewide.ipynb.

# %% ../../nbs/features/14b_fsr_genomewide.ipynb #1699fd47
from __future__ import annotations
import pandas as pd
import structlog
from ..eval_engine import FeatureEvaluator

log = structlog.get_logger()


# %% auto #0
__all__ = ['log', 'FSREvaluator']

# %% ../../nbs/features/14b_fsr_genomewide.ipynb #3a85e316
class FSREvaluator(FeatureEvaluator):
    """Extracts the short/long fragment size ratio across predefined structural metrics."""

    name = "FsrGenomewide"
    source_file = ".FSR.parquet"
    tier = 1
    category = "fragmentation"

    def extract(self, df: pd.DataFrame) -> dict[str, float]:
        extracted = {}
        try:
            if df.empty:
                return extracted

            cols = set(df.columns)
            target_metrics = [
                "short_long_ratio",
                "short_long_log2",
                "short_frac",
                "long_frac",
            ]

            for m in target_metrics:
                if m in cols:
                    extracted[f"global_{m}"] = float(df[m].median())

            return extracted
        except Exception as e:
            log.exception("extraction_failed", evaluator=self.name, error=str(e))
            return {}
