# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/features/19_mds.ipynb.

# %% ../../nbs/features/19_mds.ipynb #6ae6f0c6
from __future__ import annotations
import pandas as pd
import structlog
from ..eval_engine import FeatureEvaluator

log = structlog.get_logger()

# %% auto #0
__all__ = ["log", "MDSOnTargetEvaluator"]


# %% ../../nbs/features/19_mds.ipynb #c34b7afe
class MDSOnTargetEvaluator(FeatureEvaluator):
    """On-target MDS signature.

    Extracts ALL numeric columns from the single-row MDS on-target parquet
    rather than just the 2 originally hardcoded scalars.
    """

    name = "MdsOnTarget"
    source_file = ".MDS.ontarget.parquet"
    tier = 2
    category = "epigenetics_and_geometry"

    def extract(self, df: pd.DataFrame) -> dict[str, float]:
        extracted = {}
        try:
            if df.empty:
                return extracted

            # Extract all numeric columns from the (typically 1-row) MDS parquet
            for col in df.select_dtypes(include="number").columns:
                val = df[col].iloc[0]
                if pd.notna(val):
                    safe_col = str(col).replace(" ", "_").replace("-", "_")
                    extracted[f"mds_ontarget_{safe_col}"] = float(val)

            return extracted
        except Exception as e:
            log.exception("extraction_failed", evaluator=self.name, error=str(e))
            return {}
