# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/features/20_mds_gene.ipynb.

# %% ../../nbs/features/20_mds_gene.ipynb #ace0f2d6
from __future__ import annotations
import pandas as pd
import structlog
from ..eval_engine import FeatureEvaluator

log = structlog.get_logger()


# %% auto #0
__all__ = ['log', 'MDSGeneEvaluator']

# %% ../../nbs/features/20_mds_gene.ipynb #0831bfc4
class MDSGeneEvaluator(FeatureEvaluator):
    """Gene-specific MDS signatures."""
    
    name = "MDSGene"
    source_file = ".MDS.gene.parquet"
    tier = 2
    category = "epigenetics_and_geometry"

    def extract(self, df: pd.DataFrame) -> dict[str, float]:
        extracted = {}
        try:
            if df.empty:
                return extracted
            cols = set(df.columns)

            if "gene" in cols:
                metrics = [c for c in ["mds_mean", "mds_e1", "mds_std", "mds_z", "mds_e1_z"] if c in cols]
                for row in df.to_dict('records'):
                    g = str(row["gene"]).replace(" ", "_").replace("-","_")
                    if g == "NAN": continue
                    for m in metrics:
                        if pd.notna(row[m]):
                            extracted[f"{g}_{m}"] = float(row[m])
    
            return extracted
        except Exception as e:
            log.exception("extraction_failed", evaluator=self.name, error=str(e))
            return {}

