# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/features/20_mds_gene.ipynb.

# %% ../../nbs/features/20_mds_gene.ipynb #ace0f2d6
from __future__ import annotations
import pandas as pd
import structlog
from ..eval_engine import FeatureEvaluator

log = structlog.get_logger()

# %% auto #0
__all__ = ['log', 'MDSGeneEvaluator']

# %% ../../nbs/features/20_mds_gene.ipynb #0831bfc4
class MDSGeneEvaluator(FeatureEvaluator):
    """Gene-specific MDS signatures with cross-gene distribution statistics.

    Per-gene metrics: mds_mean, mds_e1, mds_std, mds_z, mds_e1_z
    Cross-gene derived: z-score std/skew, fraction of genes diverged (|z|>2)
    """

    name = "MDSGene"
    source_file = ".MDS.gene.parquet"
    tier = 2
    category = "epigenetics_and_geometry"

    def extract(self, df: pd.DataFrame) -> dict[str, float]:
        extracted = {}
        try:
            if df.empty:
                return extracted
            cols = set(df.columns)

            # Per-gene extraction
            if "gene" in cols:
                metrics = [
                    c
                    for c in ["mds_mean", "mds_e1", "mds_std", "mds_z", "mds_e1_z"]
                    if c in cols
                ]
                for row in df.to_dict("records"):
                    g = str(row["gene"]).replace(" ", "_").replace("-", "_")
                    if g == "NAN":
                        continue
                    for m in metrics:
                        if pd.notna(row[m]):
                            extracted[f"{g}_{m}"] = float(row[m])

            # --- Cross-gene distribution statistics ---
            if "mds_z" in cols:
                z_vals = df["mds_z"].dropna()
                if len(z_vals) > 1:
                    extracted["mds_gene_z_mean"] = float(z_vals.mean())
                    extracted["mds_gene_z_std"] = float(z_vals.std())
                    extracted["mds_gene_z_skew"] = float(z_vals.skew())
                    extracted["mds_gene_frac_diverged"] = float(
                        (z_vals.abs() > 2).mean()
                    )

            if "mds_e1_z" in cols:
                e1z = df["mds_e1_z"].dropna()
                if len(e1z) > 1:
                    extracted["mds_gene_e1z_std"] = float(e1z.std())
                    extracted["mds_gene_e1z_frac_diverged"] = float(
                        (e1z.abs() > 2).mean()
                    )

            return extracted
        except Exception as e:
            log.exception("extraction_failed", evaluator=self.name, error=str(e))
            return {}
