# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/features/19b_mds_genomewide.ipynb.

# %% ../../nbs/features/19b_mds_genomewide.ipynb #6ae6f0c6
from __future__ import annotations
import pandas as pd
import structlog
from ..eval_engine import FeatureEvaluator

log = structlog.get_logger()


# %% auto #0
__all__ = ["log", "MDSEvaluator"]


# %% ../../nbs/features/19b_mds_genomewide.ipynb #c34b7afe
class MDSEvaluator(FeatureEvaluator):
    """Global MDS signature."""

    name = "MdsGenomewide"
    source_file = ".MDS.parquet"
    tier = 2
    category = "epigenetics_and_geometry"

    def extract(self, df: pd.DataFrame) -> dict[str, float]:
        extracted = {}
        try:
            if df.empty:
                return extracted
            cols = set(df.columns)

            if "MDS" in cols:
                extracted["global_mds"] = float(df["MDS"].mean())
            if "mds_gw_z" in cols:
                extracted["global_mds_z"] = float(df["mds_gw_z"].mean())

            return extracted
        except Exception as e:
            log.exception("extraction_failed", evaluator=self.name, error=str(e))
            return {}
