# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/features/15_ocf_ontarget.ipynb.

# %% ../../nbs/features/15_ocf_ontarget.ipynb #65eabcec
from __future__ import annotations
import pandas as pd
import structlog
from ..eval_engine import FeatureEvaluator

log = structlog.get_logger()

# %% auto #0
__all__ = ['log', 'OCFOntargetEvaluator']

# %% ../../nbs/features/15_ocf_ontarget.ipynb #c058c00a
class OCFOntargetEvaluator(FeatureEvaluator):
    """Extracts on-target OCF metrics per tissue."""

    name = "OCFOntarget"
    source_file = ".OCF.ontarget.parquet"
    tier = 2
    category = "epigenetics_and_geometry"

    def extract(self, df: pd.DataFrame) -> dict[str, float]:
        extracted = {}
        try:
            if df.empty:
                return extracted
            cols = set(df.columns)

            if "tissue" in cols:
                for row in df.to_dict("records"):
                    t = str(row["tissue"]).replace(" ", "_")
                    if "OCF" in cols and pd.notna(row["OCF"]):
                        extracted[f"{t}_OCF"] = float(row["OCF"])
                    if "ocf_z" in cols and pd.notna(row["ocf_z"]):
                        extracted[f"{t}_ocf_z"] = float(row["ocf_z"])

            return extracted
        except Exception as e:
            log.exception("extraction_failed", evaluator=self.name, error=str(e))
            return {}
