# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/features/16_ocf_offtarget.ipynb.

# %% ../../nbs/features/16_ocf_offtarget.ipynb #55a8955d
from __future__ import annotations
import pandas as pd
import numpy as np
import structlog
from ..eval_engine import FeatureEvaluator

log = structlog.get_logger()

# %% auto #0
__all__ = ["log", "OCFOfftargetEvaluator"]


# %% ../../nbs/features/16_ocf_offtarget.ipynb #50f09cce
class OCFOfftargetEvaluator(FeatureEvaluator):
    """Extracts off-target OCF metrics per tissue with cross-tissue aggregates.

    Cross-tissue derived metrics:
    - max_ocf_z: highest z-score across all tissues
    - n_tissues_elevated: count of tissues with z > 2.0
    - ocf_entropy: Shannon entropy of positive z-score distribution
    """

    name = "OCFOfftarget"
    source_file = ".OCF.offtarget.parquet"
    tier = 2
    category = "epigenetics_and_geometry"

    def extract(self, df: pd.DataFrame) -> dict[str, float]:
        extracted = {}
        try:
            if df.empty:
                return extracted
            cols = set(df.columns)

            if "tissue" in cols:
                for row in df.to_dict("records"):
                    t = str(row["tissue"]).replace(" ", "_")
                    if "OCF" in cols and pd.notna(row["OCF"]):
                        extracted[f"{t}_OCF"] = float(row["OCF"])
                    if "ocf_z" in cols and pd.notna(row["ocf_z"]):
                        extracted[f"{t}_ocf_z"] = float(row["ocf_z"])

            # --- Cross-tissue aggregate metrics ---
            z_vals = {k: v for k, v in extracted.items() if k.endswith("_ocf_z")}
            if z_vals:
                z_arr = np.array(list(z_vals.values()))
                extracted["max_ocf_z_offtarget"] = float(np.max(z_arr))
                extracted["n_tissues_elevated_offtarget"] = float(np.sum(z_arr > 2.0))

                z_pos = z_arr[z_arr > 0]
                if len(z_pos) > 1:
                    p = z_pos / z_pos.sum()
                    extracted["ocf_entropy_offtarget"] = float(
                        -np.sum(p * np.log2(p + 1e-10))
                    )

            return extracted
        except Exception as e:
            log.exception("extraction_failed", evaluator=self.name, error=str(e))
            return {}
