# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/features/25_wps_genomewide.ipynb.

# %% ../../nbs/features/25_wps_genomewide.ipynb #e1f79b17
from __future__ import annotations
import pandas as pd
import numpy as np
import structlog
from ..eval_engine import FeatureEvaluator, parse_array

log = structlog.get_logger()

# %% auto #0
__all__ = ["log", "WPSGenomeEvaluator", "_to_array"]


# %% ../../nbs/features/25_wps_genomewide.ipynb #a0805d34
def _to_array(val) -> np.ndarray | None:
    """Convert a parquet array value to numpy, handling all storage formats.

    Handles:
    - numpy arrays (native parquet ``list<float>``, DuckDB ``FLOAT[]``)
    - Python lists/tuples (e.g. from pandas object columns)
    - String-encoded arrays (legacy format: ``"[1.0 2.0 3.0]"``)
    - None / NaN → returns None

    Returns:
        numpy array of floats, or None if the value is empty/invalid.
    """
    if val is None:
        return None
    if isinstance(val, np.ndarray):
        return val.astype(float) if val.size > 0 else None
    if isinstance(val, (list, tuple)):
        return np.array(val, dtype=float) if len(val) > 0 else None
    if isinstance(val, str):
        parsed = parse_array(val)
        return np.array(parsed, dtype=float) if parsed else None
    # Scalar NaN check
    try:
        if pd.isna(val):
            return None
    except (TypeError, ValueError):
        pass
    log.warning("wpsgenome_unexpected_type", val_type=type(val).__name__)
    return None


# %% ../../nbs/features/25_wps_genomewide.ipynb #86f68672
class WPSGenomeEvaluator(FeatureEvaluator):
    """Extracts genome-wide WPS metrics per region_type.

    For each WPS array column (wps_nuc, wps_tf, prot_frac_nuc, prot_frac_tf)
    and each region_type (TSS, CTCF), computes aggregate statistics across
    all genomic regions of that type:

    - mean: average of per-region array means (signal level)
    - peak_valley: average of per-region (max - min) amplitude
    - std: standard deviation of per-region array means (variability)
    - mad: median absolute deviation of per-region array means (robust dispersion)

    Output features (example): ``TSS_wps_nuc_mean``, ``CTCF_prot_frac_tf_peak_valley``

    Note:
        Krewlyzer stores WPS arrays as native ``list<float>`` in parquet,
        not as string-encoded arrays. The ``extract()`` method handles
        numpy arrays directly via ``_to_array()`` — no string parsing needed.

    Note:
        FFT spectral features were evaluated and found to be redundant with
        basic stats (r=0.91–1.00 with peak_valley/std). Nucleosome periodicity
        is captured at the chromosome level by ``WPSBackgroundEvaluator``
        (NRL, periodicity_score). See ``wps_fft_analysis.md`` for details.

    Note:
        SQL pushdown (``extract_sql()``) was removed because krewlyzer stores
        WPS arrays as native ``list<float>`` (DuckDB ``FLOAT[]``), not as
        string-encoded arrays. The SQL path used ``trim(col, '[]')`` which
        cannot parse native array types. See git history for the removed code.
    """

    name = "WPSGenome"
    source_file = ".WPS.parquet"
    tier = 2
    category = "epigenetics_and_geometry"
    # Column projection: only read the 5 columns used by extract().
    # WPS parquets have many additional columns — loading all of them
    # caused OOM on genome-wide runs (~30K rows × 50+ cols per sample).
    extract_columns = [
        "region_type",
        "wps_nuc",
        "wps_tf",
        "prot_frac_nuc",
        "prot_frac_tf",
    ]
    max_chunk_rows = 2_000_000  # Aggressive chunking for genomewide WPS data

    # Array column names used by extract()
    _array_cols = ("wps_nuc", "wps_tf", "prot_frac_nuc", "prot_frac_tf")

    def extract(self, df: pd.DataFrame) -> dict[str, float]:
        """Extract WPS features aggregated per region_type.

        For each region_type (TSS, CTCF) and each array column, computes:

        - mean: average of per-region array means (signal level)
        - peak_valley: average of per-region (max - min) (nucleosome amplitude)
        - std: std of per-region array means (variability across regions)
        - mad: MAD of per-region array means (robust dispersion)

        Handles both numpy arrays (from native parquet ``list<float>``)
        and string-encoded arrays (legacy format, via ``parse_array()``).
        """
        if df.empty:
            return {}

        cols = set(df.columns)
        if "region_type" not in cols:
            log.warning(
                "wpsgenome_missing_region_type",
                evaluator=self.name,
                columns=sorted(cols),
            )
            return {}

        extracted: dict[str, float] = {}
        n_regions_processed = 0

        for rt in df["region_type"].unique():
            if rt is None:
                continue
            rt_clean = str(rt).replace(" ", "_").replace("-", "_").replace("|", "_")
            rt_df = df[df["region_type"] == rt]

            for a in self._array_cols:
                if a not in cols:
                    continue

                # Collect per-region array statistics.
                # Data can be numpy arrays (native parquet list<float>)
                # or strings (legacy format).
                row_means: list[float] = []
                row_pvs: list[float] = []

                for val in rt_df[a]:
                    arr = _to_array(val)
                    if arr is not None and len(arr) > 0:
                        row_means.append(float(np.mean(arr)))
                        row_pvs.append(float(np.max(arr) - np.min(arr)))

                if not row_means:
                    log.debug(
                        "wpsgenome_empty_column",
                        region_type=rt_clean,
                        column=a,
                        n_rows=len(rt_df),
                    )
                    continue

                means_arr = np.array(row_means)
                extracted[f"{rt_clean}_{a}_mean"] = float(np.mean(means_arr))
                extracted[f"{rt_clean}_{a}_peak_valley"] = float(np.mean(row_pvs))
                extracted[f"{rt_clean}_{a}_std"] = float(np.std(means_arr))
                extracted[f"{rt_clean}_{a}_mad"] = float(
                    np.median(np.abs(means_arr - np.median(means_arr)))
                )
                n_regions_processed += len(row_means)

        if not extracted:
            log.warning(
                "wpsgenome_no_features_extracted",
                evaluator=self.name,
                n_rows=len(df),
                region_types=df["region_type"].unique().tolist(),
            )
        else:
            log.debug(
                "wpsgenome_extracted",
                n_features=len(extracted),
                n_regions=n_regions_processed,
            )

        return extracted
