# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/features/26_wps_background.ipynb.

# %% ../../nbs/features/26_wps_background.ipynb #53477b0f
from __future__ import annotations
import pandas as pd
import structlog
from ..eval_engine import FeatureEvaluator

log = structlog.get_logger()

# %% auto #0
__all__ = ['log', 'WPSBackgroundEvaluator']

# %% ../../nbs/features/26_wps_background.ipynb #fccdac31
class WPSBackgroundEvaluator(FeatureEvaluator):
    """Extracts periodicity distances for nucleosomes."""

    name = "WPSBackground"
    source_file = ".WPS_background.parquet"
    tier = 2
    category = "epigenetics_and_geometry"

    def extract(self, df: pd.DataFrame) -> dict[str, float]:
        extracted = {}
        try:
            if df.empty:
                return extracted
            cols = set(df.columns)

            if "group_id" in cols:
                metrics = [
                    "nrl_bp",
                    "nrl_deviation_bp",
                    "periodicity_score",
                    "adjusted_score",
                    "fragment_ratio",
                ]
                for row in df.to_dict("records"):
                    gi = str(row["group_id"]).replace(" ", "_")
                    for m in metrics:
                        if m in cols and pd.notna(row[m]):
                            extracted[f"{gi}_{m}"] = float(row[m])

            return extracted
        except Exception as e:
            log.exception("extraction_failed", evaluator=self.name, error=str(e))
            return {}
