# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/kreview",
        "doc_host": "https://msk-access.github.io",
        "git_url": "https://github.com/msk-access/kreview",
        "lib_path": "kreview",
    },
    "syms": {
        "kreview.core": {
            "kreview.core.EvalRun": ("core.html#evalrun", "kreview/core.py"),
            "kreview.core.EvalRun.to_json": (
                "core.html#evalrun.to_json",
                "kreview/core.py",
            ),
            "kreview.core.LabelConfig": ("core.html#labelconfig", "kreview/core.py"),
            "kreview.core.LabelConfig.__repr__": (
                "core.html#labelconfig.__repr__",
                "kreview/core.py",
            ),
            "kreview.core.Paths": ("core.html#paths", "kreview/core.py"),
            "kreview.core.Paths.clinical_patient": (
                "core.html#paths.clinical_patient",
                "kreview/core.py",
            ),
            "kreview.core.Paths.clinical_sample": (
                "core.html#paths.clinical_sample",
                "kreview/core.py",
            ),
            "kreview.core.Paths.cna": ("core.html#paths.cna", "kreview/core.py"),
            "kreview.core.Paths.maf": ("core.html#paths.maf", "kreview/core.py"),
            "kreview.core.Paths.sv": ("core.html#paths.sv", "kreview/core.py"),
            "kreview.core.discover_available_samples": (
                "core.html#discover_available_samples",
                "kreview/core.py",
            ),
            "kreview.core.get_duckdb_conn": (
                "core.html#get_duckdb_conn",
                "kreview/core.py",
            ),
            "kreview.core.get_sample_ids": (
                "core.html#get_sample_ids",
                "kreview/core.py",
            ),
            "kreview.core.load_clinical_patient": (
                "core.html#load_clinical_patient",
                "kreview/core.py",
            ),
            "kreview.core.load_clinical_sample": (
                "core.html#load_clinical_sample",
                "kreview/core.py",
            ),
            "kreview.core.load_cna": ("core.html#load_cna", "kreview/core.py"),
            "kreview.core.load_feature_cohort": (
                "core.html#load_feature_cohort",
                "kreview/core.py",
            ),
            "kreview.core.load_maf": ("core.html#load_maf", "kreview/core.py"),
            "kreview.core.load_metadata_cohort": (
                "core.html#load_metadata_cohort",
                "kreview/core.py",
            ),
            "kreview.core.load_sample_feature": (
                "core.html#load_sample_feature",
                "kreview/core.py",
            ),
            "kreview.core.load_sample_metadata": (
                "core.html#load_sample_metadata",
                "kreview/core.py",
            ),
            "kreview.core.load_samplesheet": (
                "core.html#load_samplesheet",
                "kreview/core.py",
            ),
            "kreview.core.load_sv": ("core.html#load_sv", "kreview/core.py"),
            "kreview.core.make_variant_key": (
                "core.html#make_variant_key",
                "kreview/core.py",
            ),
        },
        "kreview.eval_engine": {
            "kreview.eval_engine.FeatureEvaluator": (
                "eval_engine.html#featureevaluator",
                "kreview/eval_engine.py",
            ),
            "kreview.eval_engine.FeatureEvaluator.extract": (
                "eval_engine.html#featureevaluator.extract",
                "kreview/eval_engine.py",
            ),
            "kreview.eval_engine.evaluate_feature": (
                "eval_engine.html#evaluate_feature",
                "kreview/eval_engine.py",
            ),
            "kreview.eval_engine.plot_density": (
                "eval_engine.html#plot_density",
                "kreview/eval_engine.py",
            ),
            "kreview.eval_engine.plot_feature_importance": (
                "eval_engine.html#plot_feature_importance",
                "kreview/eval_engine.py",
            ),
            "kreview.eval_engine.plot_feature_vs_vaf": (
                "eval_engine.html#plot_feature_vs_vaf",
                "kreview/eval_engine.py",
            ),
            "kreview.eval_engine.plot_roc_curves": (
                "eval_engine.html#plot_roc_curves",
                "kreview/eval_engine.py",
            ),
            "kreview.eval_engine.plot_threshold_sensitivity": (
                "eval_engine.html#plot_threshold_sensitivity",
                "kreview/eval_engine.py",
            ),
            "kreview.eval_engine.plot_violin": (
                "eval_engine.html#plot_violin",
                "kreview/eval_engine.py",
            ),
            "kreview.eval_engine.single_feature_model": (
                "eval_engine.html#single_feature_model",
                "kreview/eval_engine.py",
            ),
        },
        "kreview.features.fsc_binlevel": {
            "kreview.features.fsc_binlevel.FSCBinEvaluator": (
                "features/fsc_binlevel.html#fscbinevaluator",
                "kreview/features/fsc_binlevel.py",
            ),
            "kreview.features.fsc_binlevel.FSCBinEvaluator.extract": (
                "features/fsc_binlevel.html#fscbinevaluator.extract",
                "kreview/features/fsc_binlevel.py",
            ),
        },
        "kreview.features.fsc_gene": {
            "kreview.features.fsc_gene.FSCGeneEvaluator": (
                "features/fsc_gene.html#fscgeneevaluator",
                "kreview/features/fsc_gene.py",
            ),
            "kreview.features.fsc_gene.FSCGeneEvaluator.extract": (
                "features/fsc_gene.html#fscgeneevaluator.extract",
                "kreview/features/fsc_gene.py",
            ),
        },
        "kreview.features.fsc_regions": {
            "kreview.features.fsc_regions.FSCRegionsEvaluator": (
                "features/fsc_regions.html#fscregionsevaluator",
                "kreview/features/fsc_regions.py",
            ),
            "kreview.features.fsc_regions.FSCRegionsEvaluator.extract": (
                "features/fsc_regions.html#fscregionsevaluator.extract",
                "kreview/features/fsc_regions.py",
            ),
        },
        "kreview.features.fsd": {
            "kreview.features.fsd.FSDEvaluator": (
                "features/fsd.html#fsdevaluator",
                "kreview/features/fsd.py",
            ),
            "kreview.features.fsd.FSDEvaluator.extract": (
                "features/fsd.html#fsdevaluator.extract",
                "kreview/features/fsd.py",
            ),
        },
        "kreview.features.fsr": {
            "kreview.features.fsr.FSREvaluator": (
                "features/fsr.html#fsrevaluator",
                "kreview/features/fsr.py",
            ),
            "kreview.features.fsr.FSREvaluator.extract": (
                "features/fsr.html#fsrevaluator.extract",
                "kreview/features/fsr.py",
            ),
        },
        "kreview.labels": {
            "kreview.labels.CtDNALabeler": (
                "labels.html#ctdnalabeler",
                "kreview/labels.py",
            ),
            "kreview.labels.CtDNALabeler.__init__": (
                "labels.html#ctdnalabeler.__init__",
                "kreview/labels.py",
            ),
            "kreview.labels.CtDNALabeler._assign_labels": (
                "labels.html#ctdnalabeler._assign_labels",
                "kreview/labels.py",
            ),
            "kreview.labels.CtDNALabeler._load_data": (
                "labels.html#ctdnalabeler._load_data",
                "kreview/labels.py",
            ),
            "kreview.labels.CtDNALabeler.label_all": (
                "labels.html#ctdnalabeler.label_all",
                "kreview/labels.py",
            ),
            "kreview.labels.CtDNALabeler.relabel": (
                "labels.html#ctdnalabeler.relabel",
                "kreview/labels.py",
            ),
            "kreview.labels.CtDNALabeler.summary": (
                "labels.html#ctdnalabeler.summary",
                "kreview/labels.py",
            ),
            "kreview.labels._build_patient_impact_variants": (
                "labels.html#_build_patient_impact_variants",
                "kreview/labels.py",
            ),
            "kreview.labels.compute_cna_summary": (
                "labels.html#compute_cna_summary",
                "kreview/labels.py",
            ),
            "kreview.labels.compute_impact_match": (
                "labels.html#compute_impact_match",
                "kreview/labels.py",
            ),
            "kreview.labels.compute_snv_summary": (
                "labels.html#compute_snv_summary",
                "kreview/labels.py",
            ),
            "kreview.labels.compute_sv_summary": (
                "labels.html#compute_sv_summary",
                "kreview/labels.py",
            ),
        },
    },
}
