# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/kreview",
        "doc_host": "https://msk-access.github.io",
        "git_url": "https://github.com/msk-access/kreview",
        "lib_path": "kreview",
    },
    "syms": {
        "kreview.core": {
            "kreview.core.EvalRun": ("core.html#evalrun", "kreview/core.py"),
            "kreview.core.EvalRun.to_json": (
                "core.html#evalrun.to_json",
                "kreview/core.py",
            ),
            "kreview.core.LabelConfig": ("core.html#labelconfig", "kreview/core.py"),
            "kreview.core.LabelConfig.__repr__": (
                "core.html#labelconfig.__repr__",
                "kreview/core.py",
            ),
            "kreview.core.Paths": ("core.html#paths", "kreview/core.py"),
            "kreview.core.Paths.clinical_patient": (
                "core.html#paths.clinical_patient",
                "kreview/core.py",
            ),
            "kreview.core.Paths.clinical_sample": (
                "core.html#paths.clinical_sample",
                "kreview/core.py",
            ),
            "kreview.core.Paths.cna": ("core.html#paths.cna", "kreview/core.py"),
            "kreview.core.Paths.maf": ("core.html#paths.maf", "kreview/core.py"),
            "kreview.core.Paths.sv": ("core.html#paths.sv", "kreview/core.py"),
            "kreview.core.discover_available_samples": (
                "core.html#discover_available_samples",
                "kreview/core.py",
            ),
            "kreview.core.get_duckdb_conn": (
                "core.html#get_duckdb_conn",
                "kreview/core.py",
            ),
            "kreview.core.get_sample_ids": (
                "core.html#get_sample_ids",
                "kreview/core.py",
            ),
            "kreview.core.load_clinical_patient": (
                "core.html#load_clinical_patient",
                "kreview/core.py",
            ),
            "kreview.core.load_clinical_sample": (
                "core.html#load_clinical_sample",
                "kreview/core.py",
            ),
            "kreview.core.load_cna": ("core.html#load_cna", "kreview/core.py"),
            "kreview.core.load_feature_cohort": (
                "core.html#load_feature_cohort",
                "kreview/core.py",
            ),
            "kreview.core.load_maf": ("core.html#load_maf", "kreview/core.py"),
            "kreview.core.load_metadata_cohort": (
                "core.html#load_metadata_cohort",
                "kreview/core.py",
            ),
            "kreview.core.load_sample_feature": (
                "core.html#load_sample_feature",
                "kreview/core.py",
            ),
            "kreview.core.load_sample_metadata": (
                "core.html#load_sample_metadata",
                "kreview/core.py",
            ),
            "kreview.core.load_samplesheet": (
                "core.html#load_samplesheet",
                "kreview/core.py",
            ),
            "kreview.core.load_sv": ("core.html#load_sv", "kreview/core.py"),
            "kreview.core.make_variant_key": (
                "core.html#make_variant_key",
                "kreview/core.py",
            ),
        }
    },
}
