# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_labels.ipynb.

# %% ../nbs/01_labels.ipynb #7ff8bea8
from __future__ import annotations
import pandas as pd
import numpy as np
import structlog

from kreview.core import (
    LabelConfig,
    Paths,
    IMPACT_PANELS,
    make_variant_key,
    load_samplesheet,
    load_maf,
    load_sv,
    load_cna,
    load_clinical_sample,
    load_clinical_patient,
)

log = structlog.get_logger()

# %% auto #0
__all__ = [
    "log",
    "load_ch_hotspots",
    "compute_impact_match",
    "compute_snv_summary",
    "compute_sv_summary",
    "compute_cna_summary",
    "CtDNALabeler",
]

# %% ../nbs/01_labels.ipynb #ch_hotspots
from pathlib import Path as _Path


def load_ch_hotspots(ch_maf_path: _Path | str) -> set[tuple]:
    """Load a CH hotspot MAF file and return a set of variant keys.

    The MAF file must have columns: Hugo_Symbol, Chromosome,
    Start_Position, Reference_Allele, Tumor_Seq_Allele2.

    Each row is converted to a (chrom, pos, ref, alt) tuple for fast
    lookup during SNV summary computation.
    """
    try:
        ch_df = pd.read_csv(ch_maf_path, sep="\t", comment="#")
        required = {
            "Chromosome",
            "Start_Position",
            "Reference_Allele",
            "Tumor_Seq_Allele2",
        }
        missing = required - set(ch_df.columns)
        if missing:
            raise ValueError(f"CH hotspot MAF missing required columns: {missing}")

        ch_set = set()
        for _, row in ch_df.iterrows():
            ch_set.add(
                (
                    str(row["Chromosome"]),
                    int(row["Start_Position"]),
                    str(row["Reference_Allele"]),
                    str(row["Tumor_Seq_Allele2"]),
                )
            )

        log.info(
            "ch_hotspots_loaded",
            path=str(ch_maf_path),
            n_hotspots=len(ch_set),
        )
        return ch_set
    except Exception as e:
        log.error("ch_hotspot_load_failed", path=str(ch_maf_path), error=str(e))
        raise


# %% ../nbs/01_labels.ipynb #6333e679
def _build_patient_impact_variants(
    maf: pd.DataFrame,
    clinical: pd.DataFrame,
) -> dict[str, set[tuple]]:
    """Build a lookup: patient_id → set of somatic variant keys from IMPACT samples."""
    try:
        impact_samples = clinical[clinical["GENE_PANEL"].isin(IMPACT_PANELS)][
            ["SAMPLE_ID", "PATIENT_ID"]
        ]

        impact_maf = maf[
            (maf["Tumor_Sample_Barcode"].isin(set(impact_samples["SAMPLE_ID"])))
            & (maf["Mutation_Status"] == "SOMATIC")
        ].copy()

        if impact_maf.empty:
            log.warning("no_impact_somatic_variants", n_samples=len(impact_samples))
            return {}

        impact_maf = impact_maf.merge(
            impact_samples,
            left_on="Tumor_Sample_Barcode",
            right_on="SAMPLE_ID",
            how="inner",
        )

        impact_maf["variant_key"] = make_variant_key(impact_maf)

        result = impact_maf.groupby("PATIENT_ID")["variant_key"].apply(set).to_dict()
        log.info(
            "built_impact_lookup",
            n_patients=len(result),
            n_variant_keys=sum(len(v) for v in result.values()),
        )
        return result
    except Exception as e:
        log.error("impact_lookup_build_failed", error=str(e))
        raise


def compute_impact_match(
    eligible_ids: set[str],
    maf: pd.DataFrame,
    clinical: pd.DataFrame,
) -> pd.DataFrame:
    """For each eligible ACCESS sample, check if any somatic variant (any VAF)
    also appears in the same patient's IMPACT tissue sample.
    """
    try:
        access_patients = clinical[clinical["SAMPLE_ID"].isin(eligible_ids)][
            ["SAMPLE_ID", "PATIENT_ID"]
        ].drop_duplicates()

        patient_impact_vars = _build_patient_impact_variants(maf, clinical)
        patients_with_impact = set(patient_impact_vars.keys())

        access_maf = maf[
            (maf["Tumor_Sample_Barcode"].isin(eligible_ids))
            & (maf["Mutation_Status"] == "SOMATIC")
        ].copy()

        if len(access_maf) == 0:
            return pd.DataFrame(
                {
                    "SAMPLE_ID": list(eligible_ids),
                    "has_impact_match": False,
                    "n_impact_confirmed": 0,
                    "has_paired_impact": [
                        (
                            access_patients.loc[
                                access_patients["SAMPLE_ID"] == s, "PATIENT_ID"
                            ].iloc[0]
                            in patients_with_impact
                            if s in access_patients["SAMPLE_ID"].values
                            else False
                        )
                        for s in eligible_ids
                    ],
                }
            )

        access_maf = access_maf.merge(
            access_patients,
            left_on="Tumor_Sample_Barcode",
            right_on="SAMPLE_ID",
            how="inner",
        )

        access_maf["variant_key"] = make_variant_key(access_maf)

        access_maf["in_impact"] = access_maf.apply(
            lambda row: (
                row["PATIENT_ID"] in patient_impact_vars
                and row["variant_key"] in patient_impact_vars[row["PATIENT_ID"]]
            ),
            axis=1,
        )

        per_sample = (
            access_maf.groupby("Tumor_Sample_Barcode")
            .agg(
                has_impact_match=("in_impact", "any"),
                n_impact_confirmed=("in_impact", "sum"),
                _patient_id=("PATIENT_ID", "first"),
            )
            .reset_index()
            .rename(columns={"Tumor_Sample_Barcode": "SAMPLE_ID"})
        )
        per_sample["has_paired_impact"] = per_sample["_patient_id"].isin(
            patients_with_impact
        )
        per_sample = per_sample.drop(columns=["_patient_id"])

        missing = eligible_ids - set(per_sample["SAMPLE_ID"])
        if missing:
            missing_patients = access_patients[
                access_patients["SAMPLE_ID"].isin(missing)
            ]
            missing_df = pd.DataFrame(
                {
                    "SAMPLE_ID": list(missing),
                    "has_impact_match": False,
                    "n_impact_confirmed": 0,
                }
            )
            missing_df = missing_df.merge(missing_patients, on="SAMPLE_ID", how="left")
            missing_df["has_paired_impact"] = missing_df["PATIENT_ID"].isin(
                patients_with_impact
            )
            missing_df = missing_df.drop(columns=["PATIENT_ID"])
            per_sample = pd.concat([per_sample, missing_df], ignore_index=True)

        log.info(
            "impact_match_computed",
            matched=int(per_sample["has_impact_match"].sum()),
            paired_impact=int(per_sample["has_paired_impact"].sum()),
        )
        return per_sample
    except Exception as e:
        log.error("compute_impact_match_failed", error=str(e))
        raise


# %% ../nbs/01_labels.ipynb #41a901ed
def compute_snv_summary(
    eligible_ids: set[str],
    maf: pd.DataFrame,
    min_vaf: float = 0.01,
    min_variants: int = 1,
    ch_variants: set[tuple] | None = None,
) -> pd.DataFrame:
    """Summarize somatic SNV status per eligible sample.

    Returns one row per eligible sample with columns:
        has_snv, n_somatic_snvs, n_total_somatic_snvs,
        max_vaf, mean_vaf, std_vaf, n_ch_variants, n_non_ch_variants.

    mean_vaf and std_vaf are computed only from VAF-passing variants
    (those above ``min_vaf``), providing continuous regression targets
    for the Stage 2 Quantifier.

    If ``ch_variants`` is provided, variants matching CH hotspots are
    tagged and counted separately. n_non_ch_variants counts only
    VAF-passing, non-CH variants — the key input for CH-only demotion.
    """
    try:
        somatic = maf[
            (maf["Tumor_Sample_Barcode"].isin(eligible_ids))
            & (maf["Mutation_Status"] == "SOMATIC")
        ].copy()

        if len(somatic) == 0:
            return pd.DataFrame(
                {
                    "SAMPLE_ID": list(eligible_ids),
                    "has_snv": False,
                    "n_somatic_snvs": 0,
                    "n_total_somatic_snvs": 0,
                    "max_vaf": 0.0,
                    "mean_vaf": 0.0,
                    "std_vaf": 0.0,
                    "n_ch_variants": 0,
                    "n_non_ch_variants": 0,
                }
            )

        total_depth = somatic["t_ref_count"] + somatic["t_alt_count"]
        somatic["VAF"] = np.where(
            total_depth > 0,
            somatic["t_alt_count"] / total_depth,
            0.0,
        )

        # Tag CH hotspot variants if a reference set was provided
        if ch_variants is not None:
            somatic["is_ch"] = somatic.apply(
                lambda r: (
                    str(r.get("Chromosome", "")),
                    (
                        int(r["Start_Position"])
                        if pd.notna(r.get("Start_Position"))
                        else 0
                    ),
                    str(r.get("Reference_Allele", "")),
                    str(r.get("Tumor_Seq_Allele2", "")),
                )
                in ch_variants,
                axis=1,
            )
            log.info(
                "ch_variants_tagged",
                n_ch_hits=int(somatic["is_ch"].sum()),
                n_total_somatic=len(somatic),
            )
        else:
            somatic["is_ch"] = False

        def _agg(group: pd.DataFrame) -> pd.Series:
            passing = group[group["VAF"] >= min_vaf]
            n_ch = int(passing["is_ch"].sum()) if "is_ch" in passing.columns else 0
            n_non_ch = len(passing) - n_ch
            return pd.Series(
                {
                    "has_snv": len(passing) >= min_variants,
                    "n_somatic_snvs": len(passing),
                    "n_total_somatic_snvs": len(group),
                    "max_vaf": group["VAF"].max(),
                    "mean_vaf": (
                        float(passing["VAF"].mean()) if len(passing) > 0 else 0.0
                    ),
                    "std_vaf": float(passing["VAF"].std()) if len(passing) > 1 else 0.0,
                    "n_ch_variants": n_ch,
                    "n_non_ch_variants": n_non_ch,
                }
            )

        per_sample = (
            somatic.groupby("Tumor_Sample_Barcode")
            .apply(_agg, include_groups=False)
            .reset_index()
            .rename(columns={"Tumor_Sample_Barcode": "SAMPLE_ID"})
        )

        missing = eligible_ids - set(per_sample["SAMPLE_ID"])
        if missing:
            missing_df = pd.DataFrame(
                {
                    "SAMPLE_ID": list(missing),
                    "has_snv": False,
                    "n_somatic_snvs": 0,
                    "n_total_somatic_snvs": 0,
                    "max_vaf": 0.0,
                    "mean_vaf": 0.0,
                    "std_vaf": 0.0,
                    "n_ch_variants": 0,
                    "n_non_ch_variants": 0,
                }
            )
            per_sample = pd.concat([per_sample, missing_df], ignore_index=True)

        log.info(
            "snv_summary_computed",
            min_vaf=min_vaf,
            min_variants=min_variants,
            positive_samples=int(per_sample["has_snv"].sum()),
            cohort_mean_vaf=round(float(per_sample["mean_vaf"].mean()), 4),
            cohort_max_vaf=round(float(per_sample["max_vaf"].max()), 4),
        )
        return per_sample
    except Exception as e:
        log.error("compute_snv_summary_failed", error=str(e))
        raise


# %% ../nbs/01_labels.ipynb #c9709211
def compute_sv_summary(
    eligible_ids: set[str],
    sv_df: pd.DataFrame,
) -> pd.DataFrame:
    """Summarize somatic SV status per eligible sample (binary presence/absence)."""
    try:
        somatic_sv = sv_df[
            (sv_df["Sample_ID"].isin(eligible_ids)) & (sv_df["SV_Status"] == "SOMATIC")
        ]

        if len(somatic_sv) == 0:
            return pd.DataFrame(
                {
                    "SAMPLE_ID": list(eligible_ids),
                    "has_sv": False,
                    "n_somatic_svs": 0,
                }
            )

        per_sample = (
            somatic_sv.groupby("Sample_ID")
            .agg(
                has_sv=("SV_Status", lambda x: True),
                n_somatic_svs=("SV_Status", "count"),
            )
            .reset_index()
            .rename(columns={"Sample_ID": "SAMPLE_ID"})
        )

        missing = eligible_ids - set(per_sample["SAMPLE_ID"])
        if missing:
            missing_df = pd.DataFrame(
                {
                    "SAMPLE_ID": list(missing),
                    "has_sv": False,
                    "n_somatic_svs": 0,
                }
            )
            per_sample = pd.concat([per_sample, missing_df], ignore_index=True)

        log.info(
            "sv_summary_computed", somatic_sv_samples=int(per_sample["has_sv"].sum())
        )
        return per_sample
    except Exception as e:
        log.error("compute_sv_summary_failed", error=str(e))
        raise


# %% ../nbs/01_labels.ipynb #e5ce6bcf
def compute_cna_summary(
    eligible_ids: set[str],
    cna_df: pd.DataFrame,
) -> pd.DataFrame:
    """Summarize CNA status per eligible sample."""
    try:
        present = [s for s in eligible_ids if s in cna_df.columns]
        absent = eligible_ids - set(present)

        rows = []
        for sample_id in present:
            col = cna_df[sample_id]
            n_events = (col.fillna(0) != 0).sum()
            rows.append(
                {
                    "SAMPLE_ID": sample_id,
                    "has_cna": n_events > 0,
                    "n_cna_events": int(n_events),
                }
            )

        for sample_id in absent:
            rows.append(
                {
                    "SAMPLE_ID": sample_id,
                    "has_cna": False,
                    "n_cna_events": 0,
                }
            )

        result = pd.DataFrame(rows)
        log.info(
            "cna_summary_computed",
            positive_samples=int(result["has_cna"].sum()),
            present_in_matrix=len(present),
            absent_from_matrix=len(absent),
        )
        return result
    except Exception as e:
        log.error("compute_cna_summary_failed", error=str(e))
        raise


# %% ../nbs/01_labels.ipynb #439dcd7c
class CtDNALabeler:
    """Assigns 6-tier ctDNA labels to ACCESS cfDNA samples.

    Tiers: True ctDNA+, Possible ctDNA+, Possible ctDNA−,
           Healthy Normal, Undetermined, Insufficient Data.

    Features:
        - IMPACT tissue rescue for True ctDNA+ confirmation
        - Continuous VAF regression targets (mean_vaf, std_vaf)
        - Optional CH hotspot filtering: samples whose only
          somatic evidence is clonal hematopoiesis are labeled
          ``Undetermined`` and excluded from binary classification
    """

    LABEL_TRUE_POS = "True ctDNA+"
    LABEL_POSS_POS = "Possible ctDNA+"
    LABEL_POSS_NEG = "Possible ctDNA−"
    LABEL_HEALTHY = "Healthy Normal"
    LABEL_INSUF_DATA = "Insufficient Data"
    LABEL_UNDETERMINED = "Undetermined"

    def __init__(self, paths: Paths, config: LabelConfig = LabelConfig()):
        self.paths = paths
        self.config = config
        self._load_data()

    def _load_data(self):
        if self.paths.krewlyzer_dirs:
            from kreview.core import load_metadata_cohort

            self.metadata_df = load_metadata_cohort(
                self.paths.krewlyzer_dirs, chunk_size=self.config.chunk_size
            )
        else:
            self.metadata_df = pd.DataFrame(columns=["sample_id", "total_fragments_pf"])
        log.info("loading_labeler_data", config=repr(self.config))

        self.cancer_ss = load_samplesheet(self.paths.cancer_samplesheet)
        self.healthy_xs1_ss = load_samplesheet(self.paths.healthy_xs1_samplesheet)
        self.healthy_xs2_ss = load_samplesheet(self.paths.healthy_xs2_samplesheet)

        cancer_sample_ids = set(self.cancer_ss["sample"])
        self.healthy_ids = {
            "XS1": self.healthy_xs1_ss["sample"].tolist(),
            "XS2": self.healthy_xs2_ss["sample"].tolist(),
        }

        self.clinical_sample = load_clinical_sample(self.paths.clinical_sample)
        access_clinical = self.clinical_sample[
            self.clinical_sample["GENE_PANEL"].isin(self.config.access_panels)
        ]
        self.eligible = access_clinical[
            access_clinical["SAMPLE_ID"].isin(cancer_sample_ids)
        ].copy()
        self.eligible_ids = set(self.eligible["SAMPLE_ID"])

        self.clinical_patient = load_clinical_patient(self.paths.clinical_patient)
        self.maf = load_maf(self.paths.maf)
        self.sv = load_sv(self.paths.sv)
        self.cna = load_cna(self.paths.cna)

        self._impact_df = compute_impact_match(
            self.eligible_ids, self.maf, self.clinical_sample
        )
        self._sv_df = compute_sv_summary(self.eligible_ids, self.sv)
        self._cna_df = compute_cna_summary(self.eligible_ids, self.cna)
        # Load CH hotspots if configured
        self._ch_variants = None
        if self.config.ch_hotspot_maf is not None:
            self._ch_variants = load_ch_hotspots(self.config.ch_hotspot_maf)

        self._snv_df = compute_snv_summary(
            self.eligible_ids,
            self.maf,
            min_vaf=self.config.min_vaf,
            min_variants=self.config.min_variants,
            ch_variants=self._ch_variants,
        )

    def _assign_labels(self, snv_df: pd.DataFrame) -> pd.DataFrame:
        try:
            labels = self.eligible[
                [
                    "SAMPLE_ID",
                    "PATIENT_ID",
                    "CANCER_TYPE",
                    "CANCER_TYPE_DETAILED",
                    "ONCOTREE_CODE",
                    "SAMPLE_TYPE",
                    "GENE_PANEL",
                ]
            ].copy()

            assay_map = dict(zip(self.cancer_ss["sample"], self.cancer_ss["assay"]))
            labels["access_version"] = labels["SAMPLE_ID"].map(assay_map).str.upper()

            labels = labels.merge(self._impact_df, on="SAMPLE_ID", how="left")
            labels = labels.merge(snv_df, on="SAMPLE_ID", how="left")
            labels = labels.merge(self._sv_df, on="SAMPLE_ID", how="left")
            labels = labels.merge(self._cna_df, on="SAMPLE_ID", how="left")

            bool_cols = [
                "has_impact_match",
                "has_snv",
                "has_sv",
                "has_cna",
                "has_paired_impact",
            ]
            for col in bool_cols:
                labels[col] = labels[col].fillna(False).astype(bool)

            int_cols = [
                "n_impact_confirmed",
                "n_somatic_snvs",
                "n_total_somatic_snvs",
                "n_somatic_svs",
                "n_cna_events",
                "n_ch_variants",
                "n_non_ch_variants",
            ]
            for col in int_cols:
                labels[col] = labels[col].fillna(0).astype(int)

            labels["max_vaf"] = labels["max_vaf"].fillna(0.0)
            labels["mean_vaf"] = labels["mean_vaf"].fillna(0.0)
            labels["std_vaf"] = labels["std_vaf"].fillna(0.0)

            labels["label"] = self.LABEL_POSS_NEG

            # Apply Insufficient Data fallback for 0 signal + low depth
            if not self.metadata_df.empty:
                # Resolve col name (schema changed in v0.8.2)
                tf_col = (
                    "total_fragments_pf"
                    if "total_fragments_pf" in self.metadata_df.columns
                    else "total_fragments"
                )
                merged_cols = ["sample_id", tf_col]
                if "assay" in self.metadata_df.columns:
                    merged_cols.append("assay")
                labels = labels.merge(
                    self.metadata_df[merged_cols],
                    left_on="SAMPLE_ID",
                    right_on="sample_id",
                    how="left",
                )
                labels["total_fragments_pf"] = labels[tf_col].fillna(0)
                insufficient = (
                    (~labels["has_snv"])
                    & (~labels["has_sv"])
                    & (~labels["has_cna"])
                    & (labels["total_fragments_pf"] < self.config.min_fragments)
                )
                labels.loc[insufficient, "label"] = self.LABEL_INSUF_DATA

            is_possible_pos = labels["has_snv"]
            labels.loc[is_possible_pos, "label"] = self.LABEL_POSS_POS

            # CH-only labeling: if a sample's only somatic evidence is CH
            # hotspot variants (n_non_ch_variants == 0) and it has no
            # SV/CNA/IMPACT tissue match, label as Undetermined.
            # These are biologically ambiguous — mutations were detected
            # but all are clonal hematopoiesis, not tumor-derived.
            # "Undetermined" is NOT in _MODEL_LABELS, so these samples
            # are automatically excluded from binary classification.
            ch_only = (
                (labels["label"] == self.LABEL_POSS_POS)
                & (labels["n_non_ch_variants"] == 0)
                & (~labels["has_impact_match"])
                & (~labels["has_sv"])
                & (~labels["has_cna"])
            )
            n_undetermined = int(ch_only.sum())
            if n_undetermined > 0:
                labels.loc[ch_only, "label"] = self.LABEL_UNDETERMINED
                log.warning(
                    "ch_only_undetermined",
                    n_undetermined=n_undetermined,
                    msg=(
                        "Samples with only CH variants labeled Undetermined "
                        "(excluded from binary classification)"
                    ),
                )

            is_true_pos = (
                labels["has_impact_match"] | labels["has_sv"] | labels["has_cna"]
            )
            labels.loc[is_true_pos, "label"] = self.LABEL_TRUE_POS

            return labels
        except Exception as e:
            log.error("label_assignment_failed", error=str(e))
            raise

    def _build_healthy_df(self, vaf_used: float, nvars_used: int) -> pd.DataFrame:
        """Build the healthy volunteer DataFrame — single source of truth (H-05)."""
        rows = []
        for version, sample_ids in self.healthy_ids.items():
            for sid in sample_ids:
                rows.append(
                    {
                        "SAMPLE_ID": sid,
                        "PATIENT_ID": np.nan,
                        "label": self.LABEL_HEALTHY,
                        "has_impact_match": False,
                        "has_snv": False,
                        "has_sv": False,
                        "has_cna": False,
                        "has_paired_impact": False,
                        "max_vaf": 0.0,
                        "mean_vaf": 0.0,
                        "std_vaf": 0.0,
                        "n_impact_confirmed": 0,
                        "n_somatic_snvs": 0,
                        "n_total_somatic_snvs": 0,
                        "n_somatic_svs": 0,
                        "n_cna_events": 0,
                        "n_ch_variants": 0,
                        "n_non_ch_variants": 0,
                        "access_version": version,
                        "CANCER_TYPE": np.nan,
                        "CANCER_TYPE_DETAILED": np.nan,
                        "ONCOTREE_CODE": np.nan,
                        "SAMPLE_TYPE": np.nan,
                        "GENE_PANEL": np.nan,
                        "min_vaf_used": vaf_used,
                        "min_variants_used": nvars_used,
                    }
                )
        return pd.DataFrame(rows)

    def _assign_train_test_split(
        self,
        labels: pd.DataFrame,
        test_size: float = 0.2,
        random_state: int = 42,
    ) -> pd.DataFrame:
        """Assign train/test split to labels, stratified by label tier.

        Adds a ``split`` column ('train' or 'test') to the DataFrame.
        The split is deterministic (seeded by ``random_state``) and
        stratified per label to preserve class proportions in both sets.

        Samples with labels NOT in ``_MODEL_LABELS`` (e.g. 'Undetermined',
        'Insufficient Data') are excluded from the split (split='exclude').

        Args:
            labels: DataFrame with a 'label' column.
            test_size: Fraction of modelable samples for holdout (default 0.2).
            random_state: Seed for reproducible splits.

        Returns:
            DataFrame with added 'split' column.
        """
        from kreview.selection import _MODEL_LABELS
        from sklearn.model_selection import StratifiedShuffleSplit

        labels["split"] = "exclude"

        # Only split modelable samples (those with labels used in training)
        modelable_mask = labels["label"].isin(_MODEL_LABELS)
        n_modelable = int(modelable_mask.sum())

        if n_modelable < 20:
            log.warning(
                "insufficient_samples_for_split",
                n_modelable=n_modelable,
                action="all samples assigned to train",
            )
            labels.loc[modelable_mask, "split"] = "train"
            return labels

        modelable_labels = labels.loc[modelable_mask, "label"]

        # Check if any class has fewer than 2 samples
        min_class_count = modelable_labels.value_counts().min()
        if min_class_count < 2:
            log.warning(
                "class_too_small_for_stratified_split",
                min_class_count=min_class_count,
                action="all samples assigned to train",
            )
            labels.loc[modelable_mask, "split"] = "train"
            return labels

        sss = StratifiedShuffleSplit(
            n_splits=1, test_size=test_size, random_state=random_state
        )
        modelable_idx = labels.index[modelable_mask]

        for train_idx, test_idx in sss.split(modelable_idx, modelable_labels):
            labels.loc[modelable_idx[train_idx], "split"] = "train"
            labels.loc[modelable_idx[test_idx], "split"] = "test"

        n_train = int((labels["split"] == "train").sum())
        n_test = int((labels["split"] == "test").sum())
        n_exclude = int((labels["split"] == "exclude").sum())

        log.info(
            "train_test_split_assigned",
            n_train=n_train,
            n_test=n_test,
            n_exclude=n_exclude,
            test_fraction=round(n_test / max(1, n_train + n_test), 3),
            random_state=random_state,
            train_label_dist=labels.loc[labels["split"] == "train", "label"]
            .value_counts()
            .to_dict(),
            test_label_dist=labels.loc[labels["split"] == "test", "label"]
            .value_counts()
            .to_dict(),
        )

        return labels

    def label_all(self) -> pd.DataFrame:
        try:
            cancer_labels = self._assign_labels(self._snv_df)
            cancer_labels["min_vaf_used"] = self.config.min_vaf
            cancer_labels["min_variants_used"] = self.config.min_variants

            healthy_df = self._build_healthy_df(
                self.config.min_vaf, self.config.min_variants
            )
            all_labels = pd.concat([cancer_labels, healthy_df], ignore_index=True)

            # Assign train/test split (persisted in labels.parquet)
            all_labels = self._assign_train_test_split(all_labels)

            counts = all_labels["label"].value_counts().to_dict()
            log.info("labeling_complete", distribution=counts)
            return all_labels
        except Exception as e:
            log.error("label_all_failed", error=str(e))
            raise

    def relabel(
        self, min_vaf: float | None = None, min_variants: int | None = None
    ) -> pd.DataFrame:
        try:
            vaf = min_vaf if min_vaf is not None else self.config.min_vaf
            nvars = (
                min_variants if min_variants is not None else self.config.min_variants
            )

            log.info("relabeling", min_vaf=vaf, min_variants=nvars)
            new_snv = compute_snv_summary(
                self.eligible_ids,
                self.maf,
                min_vaf=vaf,
                min_variants=nvars,
                ch_variants=self._ch_variants,
            )

            cancer_labels = self._assign_labels(new_snv)
            cancer_labels["min_vaf_used"] = vaf
            cancer_labels["min_variants_used"] = nvars

            healthy_df = self._build_healthy_df(vaf, nvars)
            all_labels = pd.concat([cancer_labels, healthy_df], ignore_index=True)

            counts = all_labels["label"].value_counts().to_dict()
            log.info("relabel_complete", distribution=counts)
            return all_labels
        except Exception as e:
            log.error("relabel_failed", error=str(e))
            raise

    def summary(self) -> dict:
        labels = self.label_all()
        positive_mask = labels["label"].isin([self.LABEL_TRUE_POS, self.LABEL_POSS_POS])
        return {
            "total_samples": len(labels),
            "label_counts": labels["label"].value_counts().to_dict(),
            "by_criterion": {
                "has_impact_match": int(labels["has_impact_match"].sum()),
                "has_snv": int(labels["has_snv"].sum()),
                "has_sv": int(labels["has_sv"].sum()),
                "has_cna": int(labels["has_cna"].sum()),
                "has_paired_impact": int(labels["has_paired_impact"].sum()),
            },
            "vaf_stats": {
                "cohort_mean_vaf": round(float(labels["mean_vaf"].mean()), 4),
                "positive_mean_vaf": (
                    round(float(labels.loc[positive_mask, "mean_vaf"].mean()), 4)
                    if positive_mask.any()
                    else 0.0
                ),
                "cohort_max_vaf": round(float(labels["max_vaf"].max()), 4),
            },
            "ch_filtering": {
                "enabled": self.config.ch_hotspot_maf is not None,
                "n_ch_demoted": (
                    int(
                        (labels["n_ch_variants"] > 0).sum()
                        - (labels["n_non_ch_variants"] > 0).sum()
                    )
                    if self.config.ch_hotspot_maf is not None
                    else 0
                ),
                "total_ch_variants": int(labels["n_ch_variants"].sum()),
            },
            "by_panel": labels.groupby("access_version")["label"]
            .value_counts()
            .unstack(fill_value=0)
            .to_dict(),
            "config": repr(self.config),
        }
