# AUTOGENERATED! DO NOT EDIT! File to edit: standalone (no notebook).
"""Global reproducibility seeding for kreview.

Provides :func:`seed_everything` to set deterministic seeds across Python's
``random`` module and PyTorch (when available).  NumPy randomness is
intentionally **not** set globally — it flows through local ``random_state``
parameters in all kreview functions to avoid side effects on third-party
libraries.
"""

# %% auto 0
__all__ = ["seed_everything"]

# %% ../nbs/standalone
import os
import random

import structlog

log = structlog.get_logger()


def seed_everything(seed: int = 42, deterministic: bool = True) -> int:
    """Set seeds across Python and (optionally) PyTorch for reproducibility.

    NumPy randomness is intentionally NOT set globally — it flows through
    local ``random_state`` parameters in all kreview functions to avoid
    side effects on third-party libraries.

    Args:
        seed: Integer seed value.
        deterministic: If True, enable PyTorch deterministic mode
            (``cudnn.deterministic=True``, ``benchmark=False``).  Trades
            ~10–20 % GPU speed for bit-exact reproducibility.  Default True.

    Returns:
        The seed that was set (for logging/provenance).
    """
    # ── Python stdlib ──
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)

    # ── PyTorch (optional — only present in [gpu] installs) ──
    try:
        import torch

        torch.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)

        if deterministic:
            torch.backends.cudnn.deterministic = True
            torch.backends.cudnn.benchmark = False
            os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"
        else:
            torch.backends.cudnn.deterministic = False
            torch.backends.cudnn.benchmark = True

        log.debug(
            "seed_torch_set",
            seed=seed,
            deterministic=deterministic,
            device=(
                str(torch.cuda.current_device()) if torch.cuda.is_available() else "cpu"
            ),
        )
    except ImportError:
        pass  # No torch — CPU-only environment is fine

    log.info("seed_everything", seed=seed, deterministic=deterministic)
    return seed
