#!/usr/bin/env python3
"""Write the standalone pipeline diagrams in ``docs/diagrams/`` from the module.

The report embeds these same layouts (``kreview.pipeline_diagram``); this script keeps
the documentation copies from becoming a second, hand-maintained source of the same
picture. Run it after changing the graph declaration:

    python3 scripts/build_diagrams.py

``tests/test_pipeline_diagram.py`` fails if the committed files fall behind.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from kreview.pipeline_diagram import pipeline_svg  # noqa: E402

OUT = REPO / "docs" / "diagrams"

PAGES = {
    "kreview-pipeline.html": (
        "standard",
        "How kreview runs",
        "Architecture · kreview · Nextflow",
        "One DAG, scattered per feature family and gathered once. Everything between the "
        "scatter and the gather runs once per family, split across CPU and GPU queues.",
    ),
    "kreview-pipeline-overview.html": (
        "overview",
        "kreview at five nodes",
        "Architecture · kreview",
        "The shortest true description of the pipeline: label, extract, the per-family "
        "fan-out, the gather, and the report.",
    ),
}

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <link href="https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=Geist:wght@400;500;600&family=Geist+Mono:wght@400;500;600&display=swap" rel="stylesheet">
  <style>
    *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
    :root {{
      --color-paper:  #f7f8fa; --color-ink: #1a2233; --color-muted: #66708a; --color-accent: #4650dc;
      --font-sans:  'Geist', -apple-system, BlinkMacSystemFont, system-ui, sans-serif;
      --font-serif: 'Instrument Serif', Georgia, serif;
      --font-mono:  'Geist Mono', ui-monospace, SFMono-Regular, Menlo, monospace;
    }}
    body {{ font-family: var(--font-sans); background: var(--color-paper); color: var(--color-ink);
      min-height: 100vh; display: flex; align-items: center; justify-content: center; padding: 3rem 2rem; }}
    .frame {{ max-width: 1200px; width: 100%; }}
    .eyebrow {{ font-family: var(--font-mono); font-size: .66rem; font-weight: 500; letter-spacing: .18em;
      text-transform: uppercase; color: var(--color-muted); margin-bottom: .5rem; }}
    h1 {{ font-family: var(--font-serif); font-size: clamp(1.5rem, 2.4vw + .75rem, 2rem); font-weight: 400;
      letter-spacing: -.02em; line-height: 1.15; margin-bottom: .5rem; }}
    .sub {{ font-size: .9rem; color: var(--color-muted); margin-bottom: 1.5rem; max-width: 68ch; line-height: 1.5; }}
    svg {{ width: 100%; min-width: 900px; display: block; }}
    .colophon {{ font-family: var(--font-mono); font-size: .62rem; letter-spacing: .1em; color: var(--color-muted);
      border-top: 1px solid rgba(26,34,51,.12); margin-top: 1.5rem; padding-top: .75rem; }}
  </style>
</head>
<body>
  <div class="frame">
    <p class="eyebrow">{eyebrow}</p>
    <h1>{title}</h1>
    <p class="sub">{sub}</p>
{svg}
    <p class="colophon">GENERATED BY SCRIPTS/BUILD_DIAGRAMS.PY — EDIT NBS/08_PIPELINE_DIAGRAM.IPYNB</p>
  </div>
</body>
</html>
"""


def render(name: str) -> str:
    level, title, eyebrow, sub = PAGES[name]
    return TEMPLATE.format(
        title=title, eyebrow=eyebrow, sub=sub, svg=pipeline_svg(level, chips=False)
    )


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for name in PAGES:
        (OUT / name).write_text(render(name))
        print("wrote", (OUT / name).relative_to(REPO))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
