name: Docs
on:
  push:
    branches: [main, develop]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[docs]
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Deploy development docs
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: |
          mike deploy --push --update-aliases dev develop

      - name: Deploy stable docs
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          VERSION=$(grep '^version =' settings.ini | cut -d '=' -f 2 | tr -d ' ')
          mike deploy --push --update-aliases "$VERSION" stable
          mike set-default --push stable

      - name: Checkout newly built gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages-export
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: gh-pages-export
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
